ci: publish: Merge branch checks from upstream publish-commit-bottles workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -28,7 +28,136 @@ on:
         description: "Message to include when autosquashing revision bumps, deletions, and rebuilds (requires autosquash)"
         required: false
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    outputs:
+      bottles: ${{ steps.pr-branch-check.outputs.bottles }}
+      head_sha: ${{ steps.pr-branch-check.outputs.head_sha }}
+      branch: ${{ steps.pr-branch-check.outputs.branch }}
+      remote_branch: ${{ steps.pr-branch-check.outputs.remote_branch }}
+      remote: ${{ steps.pr-branch-check.outputs.remote }}
+      replace: ${{ steps.pr-branch-check.outputs.replace }}
+      requires_merge: ${{ steps.pr-branch-check.outputs.requires_merge }}
+    steps:
+      - name: Check PR approval
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if jq --exit-status 'all(.[].state; .!= "APPROVED")'
+          then
+            echo "::error ::PR #$PR is not approved!"
+            exit 1
+          fi < <(
+            gh api \
+              --header 'Accept: application/vnd.github+json' \
+              --header 'X-GitHub-Api-Version: 2022-11-28' \
+              --paginate \
+              "repos/$GITHUB_REPOSITORY/pulls/$PR/reviews"
+          )
+
+      - name: Check PR branch for mergeability
+        id: pr-branch-check
+        env:
+          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
+        run: |
+          pr_data="$(
+            gh api \
+              --header 'Accept: application/vnd.github+json' \
+              --header 'X-GitHub-Api-Version: 2022-11-28' \
+              "repos/$GH_REPO/pulls/$PR"
+          )"
+
+          pushable="$(jq .maintainer_can_modify <<< "$pr_data")"
+          branch="$(jq --raw-output .head.ref <<< "$pr_data")"
+          remote="$(jq --raw-output .head.repo.clone_url <<< "$pr_data")"
+          head_repo="$(jq --raw-output .head.repo.full_name <<< "$pr_data")"
+          head_repo_owner="$(jq --raw-output .head.repo.owner.login <<< "$pr_data")"
+          head_sha="$(jq --raw-output .head.sha <<< "$pr_data")"
+          fork_type="$(jq --raw-output .head.repo.owner.type <<< "$pr_data")"
+          state="$(jq --raw-output .state <<< "$pr_data")"
+          node_id="$(jq --raw-output .node_id <<< "$pr_data")"
+          merged="$(jq --raw-output .merged <<< "$pr_data")"
+          automerge_enabled="$(jq --raw-output '.auto_merge != null' <<< "$pr_data")"
+
+          if [[ -z "$pushable" ]] ||
+             [[ -z "$branch" ]] ||
+             [[ -z "$remote" ]] ||
+             [[ -z "$head_repo" ]] ||
+             [[ -z "$head_repo_owner" ]] ||
+             [[ -z "$head_sha" ]] ||
+             [[ -z "$fork_type" ]] ||
+             [[ -z "$state" ]] ||
+             [[ -z "$merged" ]] ||
+             [[ -z "$node_id" ]] ||
+             [[ -z "$automerge_enabled" ]]
+          then
+            echo "::error ::Failed to get PR data!"
+            exit 1
+          fi
+
+          if [[ "$state" = "closed" ]]
+          then
+            echo "::error ::PR #$PR is closed!"
+            exit 1
+          fi
+
+          bottles=true
+          while IFS='' read -r label
+          do
+            if [[ "$label" = "CI-syntax-only" ]] ||
+               [[ "$label" = "CI-no-bottles" ]] ||
+               [[ "$label" = "CI-published-bottle-commits" ]]
+            then
+              echo '::notice ::No bottles to publish according to PR labels.'
+              bottles=false
+              break
+            fi
+          done < <(jq --raw-output '.labels[].name' <<< "$pr_data")
+
+          requires_merge=true
+          if [[ "$merged" = "true" || "$automerge_enabled" = "true" ]]
+          then
+            echo '::notice ::Pull request is either already merged or queued to merge.'
+            requires_merge=false
+          fi
+
+          if [[ "$branch" = "master" ]]
+          then
+            branch="$head_repo_owner/master"
+            remote_branch="master"
+          else
+            remote_branch="$branch"
+          fi
+
+          {
+            echo "bottles=$bottles"
+            echo "head_sha=$head_sha"
+            echo "branch=$branch"
+            echo "remote_branch=$remote_branch"
+            echo "remote=$remote"
+            echo "node_id=$node_id"
+            echo "requires_merge=$requires_merge"
+            echo "replace=${{ inputs.autosquash }}"
+          } >> "$GITHUB_OUTPUT"
+
+          if "$pushable" && [[ "$fork_type" != "Organization" ]] ||
+             [[ "$head_repo" = "$GH_REPO" ]] ||
+             [[ "$bottles" = "false" ]]
+          then
+            exit 0
+          elif "$pushable" || [[ "$fork_type" = "Organization" ]]
+          then
+            MESSAGE="$ORG_FORK_MESSAGE"
+          else
+            MESSAGE="$NON_PUSHABLE_MESSAGE"
+          fi
+
+          echo "replace=true" >> "$GITHUB_OUTPUT"
+          gh pr comment "$PR" --body "$MESSAGE" --repo "$GITHUB_REPOSITORY"
+          gh pr edit --add-label 'no push access' "$PR" --repo "$GITHUB_REPOSITORY"
+
   pr-pull:
+    needs: check
     if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
     strategy:
       matrix:
@@ -103,10 +232,14 @@ jobs:
         uses: Homebrew/actions/git-try-push@master
         with:
           token: ${{ secrets.LYRAPHASE_RUNNER_AUTOMERGE_TOKEN }}
-          branch: test-publish
+          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
+          remote: ${{ needs.check.outputs.remote }}
+          branch: ${{ needs.check.outputs.branch }}
+          remote_branch: ${{ needs.check.outputs.remote_branch }}
         env:
           GIT_COMMITTER_NAME: ${{ vars.LYRAPHASE_RUNNER_USER }}
           GIT_COMMITTER_EMAIL: ${{ vars.LYRAPHASE_RUNNER_EMAIL }}
+          # HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}
 
 # TODO: Find out if this permission is needed?
 # id-token: write
